trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: scaledobject_keda
  displayName: scaledobject_keda
  jobs:
  - deployment: scaledobject_keda
    displayName: scaledobject_keda
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                yes|argocd login argocd.singhritesh85.com --username admin --password $(ARGOCD_PASSWORD) --grpc-web --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd repo add https://github.com/singhritesh85/scaledobject-with-keda.git --username $(GITHUB_USERNAME) --password $(GITHUB_PASSWORD) --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd app create scaledobject-gke --project default --repo https://github.com/singhritesh85/scaledobject-with-keda.git --path ./scaledobject-with-keda --dest-namespace ordersystem --sync-option CreateNamespace=true --dest-server https://kubernetes.default.svc --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster --upsert
                argocd app sync scaledobject-gke --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl get scaledobject -n ordersystem --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl get hpa -n ordersystem --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd app create scaledobject-aks --project default --repo https://github.com/singhritesh85/scaledobject-with-keda.git --path ./trigger-authentication-scaledobject --dest-namespace postgresql --sync-option CreateNamespace=true --dest-server https://multicloud-cluster-dns-8t715zyt.hcp.eastus.azmk8s.io:443 --kube-context=multicloud-aks-cluster --upsert
                argocd app sync scaledobject-aks --kube-context=multicloud-aks-cluster
                kubectl get scaledobject -n postgresql --context=multicloud-aks-cluster
                kubectl get hpa -n postgresql --context=multicloud-aks-cluster
