---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spring-boot-producer-scaler
  namespace: ordersystem
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-service-folo
  pollingInterval: 10
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-with-kraft.kafka.svc.cluster.local:9092
      topic: order-events
      consumerGroup: order-service-group
      lagThreshold: "1"
  - type: external-push
    metadata:
      scalerAddress: keda-add-ons-http-external-scaler.keda.svc.cluster.local:9090
      deployment: order-service-folo
      service: order-service-folo
      port: "80"
      targetPendingRequests: "2"
