apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: concurrent-requests-scaler
  namespace: ordersystem
spec:
  scaleTargetRef:
    name: order-service-folo
    kind: Deployment
    apiVersion: apps/v1
    service: order-service-folo
    port: 80
  maxReplicas: 10
  minReplicas: 1
  scalingMetric:
    concurrency:
      targetValue: 2
      granularity: 1s
