apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: concurrent-requests-scaler
  namespace: ordersystem
spec:
  scaleTargetRef:
    name: order-service-folo
    kind: Deployment
    apiVersion: apps/v1
    service: order-service-folo
    port: 80
  minReplicaCount: 1
  maxReplicaCount: 10
  scalingMetric:
    concurrency:
      targetValue: 20
      granularity: 10s
